sonar.projectKey=user030501_Student-Consultation-CITE
sonar.organization=user030501
sonar.projectName=Student-Consultation-CITE

sonar.sources=lib
sonar.inclusions=lib/main.dart,lib/models/consultation_form_data.dart
sonar.tests=test
sonar.sourceEncoding=UTF-8
sonar.test.inclusions=test/**/*.dart
sonar.dart.coverage.reportPaths=coverage/lcov.info

sonar.exclusions=\
  android/**,\
  ios/**,\
  web/**,\
  frontend/**,\
  build/**,\
  .dart_tool/**,\
  **/*.g.dart,\
  **/*.freezed.dart
