sonar.projectKey=user030501_Student-Consultation-CITE
sonar.organization=user030501
sonar.projectName=Student-Consultation-CITE

sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8
sonar.test.inclusions=test/**/*.dart
sonar.dart.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=\
  android/**,\
  ios/**,\
  web/**,\
  frontend/**,\
  build/**,\
  .dart_tool/**,\
  **/*.g.dart,\
  **/*.freezed.dart

sonar.coverage.exclusions=\
  lib/main.dart,\
  lib/*_page.dart,\
  lib/data/**
